// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: idgen.proto

package errors

import (
	_ "github.com/go-kratos/kratos/v2/api/kratos/api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Idgen int32

const (
	Idgen_MissingName Idgen = 0
)

// Enum value maps for Idgen.
var (
	Idgen_name = map[int32]string{
		0: "MissingName",
	}
	Idgen_value = map[string]int32{
		"MissingName": 0,
	}
)

func (x Idgen) Enum() *Idgen {
	p := new(Idgen)
	*p = x
	return p
}

func (x Idgen) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Idgen) Descriptor() protoreflect.EnumDescriptor {
	return file_idgen_proto_enumTypes[0].Descriptor()
}

func (Idgen) Type() protoreflect.EnumType {
	return &file_idgen_proto_enumTypes[0]
}

func (x Idgen) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Idgen.Descriptor instead.
func (Idgen) EnumDescriptor() ([]byte, []int) {
	return file_idgen_proto_rawDescGZIP(), []int{0}
}

var File_idgen_proto protoreflect.FileDescriptor

var file_idgen_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x69, 0x64, 0x67, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x61,
	0x70, 0x69, 0x2e, 0x69, 0x64, 0x67, 0x65, 0x6e, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x1a,
	0x1c, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x1d, 0x0a,
	0x05, 0x49, 0x64, 0x67, 0x65, 0x6e, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6e,
	0x67, 0x4e, 0x61, 0x6d, 0x65, 0x10, 0x00, 0x1a, 0x03, 0xa0, 0x45, 0x01, 0x42, 0x2a, 0x5a, 0x17,
	0x61, 0x70, 0x69, 0x2f, 0x69, 0x64, 0x67, 0x65, 0x6e, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x3b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0xa2, 0x02, 0x0e, 0x41, 0x50, 0x49, 0x49, 0x64, 0x67,
	0x65, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idgen_proto_rawDescOnce sync.Once
	file_idgen_proto_rawDescData = file_idgen_proto_rawDesc
)

func file_idgen_proto_rawDescGZIP() []byte {
	file_idgen_proto_rawDescOnce.Do(func() {
		file_idgen_proto_rawDescData = protoimpl.X.CompressGZIP(file_idgen_proto_rawDescData)
	})
	return file_idgen_proto_rawDescData
}

var file_idgen_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_idgen_proto_goTypes = []interface{}{
	(Idgen)(0), // 0: api.idgen.errors.Idgen
}
var file_idgen_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idgen_proto_init() }
func file_idgen_proto_init() {
	if File_idgen_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idgen_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_idgen_proto_goTypes,
		DependencyIndexes: file_idgen_proto_depIdxs,
		EnumInfos:         file_idgen_proto_enumTypes,
	}.Build()
	File_idgen_proto = out.File
	file_idgen_proto_rawDesc = nil
	file_idgen_proto_goTypes = nil
	file_idgen_proto_depIdxs = nil
}
