// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"tinyid/internal/biz"
	"tinyid/internal/conf"
	"tinyid/internal/data"
	"tinyid/internal/server"
	"tinyid/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, error) {
	dataData, err := data.NewData(confData)
	if err != nil {
		return nil, err
	}
	idgenRepo := data.NewIdgenRepo(dataData, logger)
	idgenUsecase := biz.NewIdgenUsecase(idgenRepo, logger)
	idgenService := service.NewIdgenService(idgenUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, idgenService)
	grpcServer := server.NewGRPCServer(confServer, idgenService)
	app := newApp(logger, httpServer, grpcServer)
	return app, nil
}
